version: '3.8'

services:
  mirth-connect:
    image: nextgenhealthcare/connect:4.4.0
    container_name: mirth_vuln
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - DATABASE=derby
      - VMOPTIONS=-Xmx512m
    networks:
      - medinet

  pickle-service:
    build: ./pickle_service
    container_name: pickle_vuln
    ports:
      - "9090:9090"
    networks:
      - medinet

  mysql-db:
    image: mysql:5.7
    container_name: mysql_vuln
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediconnect
      MYSQL_USER: app_user
      MYSQL_PASSWORD: App2023!
    ports:
      - "3306:3306"
    networks:
      - medinet

networks:
  medinet:
    driver: bridge
